### ISSUE TITLE
Single batch job definition

### ISSUE THREAD

**Issue by Ts1n** [i-on-project/integration#126]
- Given the similarities between ISEL Timetable and Generic batch jobs, there should be a single batch job definition and when needed call specific modules, e.g. ISEL Timetable imports pdf data vs Generic imports yaml data

**Comment by rjcanto** [comment]
Due to the removal of the Generic job, this question can be reframed. Can and is it desirable that there's a single batch job definition for all types of jobs (TIMETABLE, EXAM_SCHEDULE, ACADEMIC_CALENDAR)?

**Comment by rjcanto** [comment]
No longer applicable to the current architecture.
