### ISSUE TITLE
Remove GCP from CICD pipeline

### ISSUE THREAD

**Issue by grimord** [i-on-project/integration#139]
Remove GCP deployments from all CICD pipelines.

**Comment by grimord** [comment]
Had to comment out DownloadTasklet Tests that were downloading PDF files from isel.pt which was being flagged as suspicious by the github runner and blocked. 

Have to rework IFileDownloader implementation to receive HTTP client by injection thus allowing it to be mocked for proper unit testing.

**Comment by rjcanto** [comment]
OK
Unit tests to be reviewed in issue #125
