### ISSUE TITLE
validate dependency versions

### ISSUE THREAD

**Issue by grimord** [i-on-project/integration#140]
Validate project dependency versions on [Gradle Build File](https://github.com/i-on-project/integration/blob/master/build.gradle.kts) to determine if any need to be bumped to a more recent version due to:

- Security improvements
- Added features or enhancements that could prove beneficial to the integration project
- Performance improvements

Of particular relevance should be Spring and Kotlin/JVM related dependencies.

**Comment by rjcanto** [comment]
There's a warning when Integration runs:
_Illegal reflective access by com.itextpdf.io.source.ByteBufferRandomAccessSource_

Will be addressed in this issue as well.

**Comment by rjcanto** [comment]
New versions:
Component | OLD version | NEW version
-|-|-
org.springframework.boot  | 2.2.6.RELEASE | 2.3.10.RELEASE
io.spring.dependency-management | 1.0.9.RELEASE |1.0.11.RELEASE
kotlin("jvm") | 1.3.71 | 1.4.32
kotlin("plugin.spring") | 1.3.71 | 1.4.32 
org.jlleitschuh.gradle.ktlint | 9.2.1 | 10.0.0
org.springframework.boot:spring-boot-starter-mail | 2.3.1.RELEASE | 2.3.10.RELEASE
technology.tabula:tabula |  1.0.3 | 1.0.4
com.itextpdf:kernel | 7.0.0 | 7.1.15
com.squareup.moshi:moshi-kotlin | 1.9.2  | 1.12.0
com.fasterxml.jackson.module:jackson-module-kotlin | 2.11.1 | 2.12.3
com.fasterxml.jackson.dataformat:jackson-dataformat-yaml | 2.11.1 | 2.12.3
org.springframework.batch:spring-batch-test | 4.2.2.RELEASE | 4.2.6.RELEASE
com.icegreen:greenmail | 1.5.13 | 1.6.3

After building with the new versions a test in PostUploadTaskletTest.kt was failing.
One of the assertions in `whenNoHashIsOnContext_thenThrowTypeCasExceptionAndAssertNoHashInDb` test method was validating `TypeCastException`. In version Kotlin 1.4 all runtime checks throw a `java.lang.NullPointerException` as per [Kotlin Compatibility Guide](https://kotlinlang.org/docs/compatibility-guide-14.html#unify-exceptions-from-null-checks)
