### ISSUE TITLE
Research how maven/gradle caching can be used

### ISSUE THREAD

**Issue by pmhsfelix** [i-on-project/integration#22]
Research how maven/gradle caching can be used both for:
- Docker based builds
- GitHub actions based builds

**Comment by sscosta** [comment]
The issue we are trying to solve in docker-based builds is slow local builds when running gradlew build (which includes downloading dependencies when they are not in cache) as part of the process of assembling a docker image.

A possible solution could be to follow the layered approach already proposed and include a layer containing the dependencies. That layer is cached for future builds.

Source:
https://stackoverflow.com/questions/58593661/slow-gradle-build-in-docker-caching-gradle-build

**Comment by Ts1n** [comment]
Given that this project won't have a significant amount of dependencies, we feel this is a non-issue for now.
If in the future there is evidence that shows that builds (local or in pipeline) are taking longer than they should, we will revisit this issue.
