### ISSUE TITLE
Define kotlin "check style" process

### ISSUE THREAD

**Issue by pmhsfelix** [i-on-project/integration#23]
Define kotlin checkstyle-like process, with both IDE and gradle integration.

**Comment by sscosta** [comment]
klint - https://github.com/pinterest/ktlint

Integration with gradle through plugin or with the definition of 2 tasks.

The downside is that for IDE (Intellij) integration, it is necessary to install it on the development machines. (The installation is required to use the klint CLI)

**Comment by Ts1n** [comment]
> klint - https://github.com/pinterest/ktlint
> 
> Integration with gradle through plugin or with the definition of 2 tasks.
> 
> The downside is that for IDE (Intellij) integration, it is necessary to install it on the development machines. (The installation is required to use the klint CLI)

I agree with this solution. The installation of the tool or configuration of the IDE can be part of the requirements to contribute to this project and be stated on the README.md
Regardless this will be present on the CI/CD pipeline and thus prevent 'bad code' to be merged.

**Comment by Ts1n** [comment]
Upon further investigation we decided to use [klint](https://github.com/pinterest/ktlint).
We'll add the klint [plugin](https://github.com/jlleitschuh/ktlint-gradle) to gradle, which will add tasks. To note are:
- `ktlintFormat`: Formats according to rules;
- `ktlintCheck`: Check if rules are applied.

To ensure that the same style is applied by _IntelliJ_ or _Android_ Studio there are 2 options:
- Download `klint cli` and [apply the style](https://github.com/pinterest/ktlint#option-1-recommended);
- [Edit and copy the style options](https://github.com/pinterest/ktlint#option-3) on _IntelliJ_
(both options are only done once at the start of development)

The task `ktlintCheck` will be added to the pipeline, ensuring that the code follows the style rules.

@pmhsfelix @jtrindade @palbp
