### ISSUE TITLE
Research on how to use Cloud Run for batch processes

### ISSUE THREAD

**Issue by pmhsfelix** [i-on-project/integration#24]

**Comment by sscosta** [comment]
Initially it was not taken into account cloud run's request/inactivity timeout - 15 minutes.

Running periodic jobs would be possible, but not in a standard way. External timers would have to be used, which does not seem a good option from an administration point of view.

First request overhead can be an issue for core - e.g. for login.

Another managed alternative within Google Cloud's offer: Google Kubernetes Engine.

Main concerns : costs

Conditions:
- One free cluster
- 0,10/ hour management costs (72 dollars per month)
- Compute Engine costs (~30 dollars per month for the lowest specs machine)

**Comment by Ts1n** [comment]
> Initially it was not taken into account cloud run's request/inactivity timeout - 15 minutes.
> 
> Running periodic jobs would be possible, but not in a standard way. External timers would have to be used, which does not seem a good option from an administration point of view.
> 
> First request overhead can be an issue for core - e.g. for login.
> 
> Another managed alternative within Google Cloud's offer: Google Kubernetes Engine.
> 
> Main concerns : costs
> 
> Conditions:
> 
>     * One free cluster
> 
>     * 0,10/ hour management costs (72 dollars per month)
> 
>     * Compute Engine costs (~30 dollars per month for the lowest specs machine)

The cost can be brought down a bit by using less nodes (2), US locations and shared VCPU, but there will still be a monthly cost.
But within Google Cloud's the only other alternative would be a unmanaged environment.

**Comment by sscosta** [comment]
@pmhsfelix , @jtrindade 

About hosting:

The two options considered were GKE and Compute Engine Instances.

Costs:

    - GKE - no administrative fee as we would use one regional cluster. We would be billed by the number of nodes in the cluster (e.g. 2) at the price of compute Instances.
    - VM Instance - aprox 13.8 dollars per month


Operation and administration:
    - GKE requires configuration of deployment and service objects for kubernetes. This configuration is not difficult to make. We would not have to administer the cluster and have autohealing and autoscaling capabilities. These are not necessary for our use case
    - With VM instances we would have to update OS and software periodically. We would have tighter control over the infraestructure.

Conclusion:

    - GKE offers a wide variety of functionalities which we don't need, like autoscaling and autohealing. Kubernetes is built for scalability.
    - Although there is a time cost associated with maintenance, we choose VM instances (one instance). It is sufficient to host the app container.
