### ISSUE TITLE
Create and configure Google Cloud Compute Engine

### ISSUE THREAD

**Issue by sscosta** [i-on-project/integration#29]
Create a container-optimized VM instance on Compute Engine.

Configure networking if necessary.

**Comment by Ts1n** [comment]
- Created 2 vm instances: **i-on-integration-staging** and **i-on-integration-production**
- Configured both to reserve static external IP
- Configure startup script to run Google Cloud SQL Proxy to enable connection to Google Cloud SQL Postgres instances
