### ISSUE TITLE
Create initial project structure

### ISSUE THREAD

**Issue by Ts1n** [i-on-project/integration#3]
Use [spring initializr](https://start.spring.io/) to generate base project. 
As dependencies add Spring Batch, H2 and JDBC API.

Acceptance Criteria
- [x] PR merged to master with project structure

**Comment by sscosta** [comment]
The added project builds and executes successfully. Its dependencies are according to what is advised in the "Definitive Guide to Spring Batch" and the project namespace (org.ionproject.integration) is in line with what was advised.
