### ISSUE TITLE
Timetable repeated class section

### ISSUE THREAD

**Issue by xploitedd** [i-on-project/integration#307]
The timetable currently has repeated class sections, on each class.

I believe this happens due to the way the class section is currently extracted from the PDF file, where a class section entry in the timetable corresponds to a class section event (a lecture or practice class).

Is this something that can be fixed, or should Core prepare for this behavior?

**Comment by grimord** [comment]
Created PR https://github.com/i-on-project/integration-data/pull/33 that contains updated formats with this bug fixed (hopefully). Can you check @xploitedd ?

**Comment by xploitedd** [comment]
The new data seems to be ok
