### ISSUE TITLE
Setup Google Cloud Run and Google Cloud Container Registry

### ISSUE THREAD

**Issue by Ts1n** [i-on-project/integration#6]
Acceptance Criteria:
- [x] Add PROJECT_ID to repo Secrets;
- [x] Add SERVICE-NAME to repo Secrets;
- [x] Add REGION to repo Secrets.

**Comment by sscosta** [comment]
Added to repository secrets as:
- RUN_SERVICE_NAME
- RUN_REGION

**Comment by Ts1n** [comment]
> 
> 
> Added to repository secrets as:
> 
>     * RUN_SERVICE_NAME
> 
>     * RUN_REGION

RUN_* is too generic. I would suggest GOOGLE_CLOUD_RUN_*

**Comment by Ts1n** [comment]
I'm not sure that google cloud run service can be create in region europe-* if we want to make use of google cloud container registry with the free account.

> Container Registry only charges for the Cloud Storage and network egress consumed by your Docker images
> Cloud Storage Always Free quotas apply to usage in US-WEST1, US-CENTRAL1, and US-EAST1 regions.

Sources: [https://cloud.google.com/container-registry/](https://cloud.google.com/container-registry/), [https://cloud.google.com/storage/pricing/](https://cloud.google.com/storage/pricing/)

**Comment by sscosta** [comment]
Corrected secrets according to @Ts1n suggestion and created service in a region eligible for free-tier Google Cloud Storage usage.
